### ISSUE TITLE
cannot import google.cloud.securitycenter_v1 in requirements

### ISSUE THREAD

**Issue by ALGREY-RN** [googleapis/python-securitycenter#79]
I'm trying to use this API in Cloud Function. When I use the import "from google.cloud.securitycenter_v1.proto.finding_pb2 import Finding" as shown in the code snippet, nothing I put in requirements.txt seems to satisfy the installer and it cannot find this module. When using the exact requirements.txt parameters in the example, it still cannot find the module. I am using the exact import of the examples and the same requirement, google-cloud-securitycenter==1.0.0

Any help would be appreciated.

**Comment by busunkim96** [comment]
That specific import looks like it's from the previous (<1.0.0) version of the library. What code snippet are you looking at? As far as I can tell the snippets on cloud.google.com (like the ones on https://cloud.google.com/security-command-center/docs/how-to-api-manage-notifications#python_2) are up to date with the latest release. You can also reference this directory: https://github.com/googleapis/python-securitycenter/tree/master/samples/snippets

**Comment by ALGREY-RN** [comment]
I was trying to use code I had made a month or two ago, and had not noticed the changes. Thanks!
